import {before,after,test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {PGlite} from '@electric-sql/pglite';import ts from 'typescript';import vm from 'node:vm';
let db;const user='00000000-0000-0000-0000-000000000001';
before(async()=>{db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema private;create table profiles(id uuid primary key,first_name text,last_name text,email text);create table support_messages(id uuid primary key default gen_random_uuid(),user_id uuid,sender_role text,message text,read boolean default false,created_at timestamptz default now());create table command_notifications(id uuid default gen_random_uuid(),event_key text unique,kind text check(kind in('visit','signup','test')),title text,body text,url text);create table deliveries(n int);create function private.dispatch_command_notifications() returns void language sql as 'insert into deliveries values(1)';grant all on profiles,support_messages,command_notifications to service_role;`);
for(const name of ['20261005193122_command_support_chat','20261005193134_signup_welcome_emails'])await db.exec(readFileSync(new URL('../supabase/migrations/'+name+'.sql',import.meta.url),'utf8'));
await db.query('insert into profiles values($1,$2,$3,$4)',[user,'Jamie','Test','test@example.test']);});after(async()=>await db?.close());
async function tx(fn){await db.exec('begin');try{await fn();}finally{await db.exec('rollback');}}
test('customer message queues one push with chat deep link and no message-body exposure',()=>tx(async()=>{await db.query('insert into support_messages(user_id,sender_role,message)values($1,$2,$3)',[user,'user','Private question']);const rows=(await db.query('select * from command_notifications')).rows;assert.equal(rows.length,1);assert.equal(rows[0].kind,'support');assert.equal(rows[0].url,'/command?chat='+user);assert.ok(!rows[0].body.includes('Private question'));}));
test('admin reply does not notify the owner again',()=>tx(async()=>{await db.query('insert into support_messages(user_id,sender_role,message)values($1,$2,$3)',[user,'admin','Reply']);assert.equal((await db.query('select count(*)::int n from command_notifications')).rows[0].n,0);}));
test('thread summary counts unread inbound messages only',()=>tx(async()=>{for(const sender of ['user','user','admin'])await db.query('insert into support_messages(user_id,sender_role,message)values($1,$2,$3)',[user,sender,'Test']);assert.equal(Number((await db.query('select * from command_support_threads()')).rows[0].unread),2);}));
test('new signup queues welcome once and jobs are leased against concurrent workers',()=>tx(async()=>{assert.equal((await db.query('select count(*)::int n from welcome_email_jobs')).rows[0].n,1);await db.exec('set local role service_role');assert.equal((await db.query('select * from claim_welcome_emails()')).rows.length,1);assert.equal((await db.query('select * from claim_welcome_emails()')).rows.length,0);}));
test('ordinary clients cannot read email jobs or call service-only claims',()=>tx(async()=>{await db.exec('set local role authenticated');await assert.rejects(db.query('select * from claim_welcome_emails()'),/permission denied/);}));
test('welcome template escapes customer names and avoids fixed approval promises',()=>{const exports={};vm.runInNewContext(ts.transpileModule(readFileSync(new URL('../lib/welcome-email.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports});const email=exports.welcomeEmail('<script>');assert.ok(email.html.includes('&lt;script&gt;'));assert.ok(!email.html.includes('<script>'));assert.ok(email.text.includes('Carrier review times vary'));});
