"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { authFetch } from "@/lib/auth-fetch";
import { Panel } from "../../WorkspacePrimitives";
import type { WorkspaceViewProps } from "../../WorkspaceApp";
type Member={id:string;first_name:string;last_name:string;email:string;wallet_balance:number;subscription_status:string;paused:boolean};
type Transfer={id:string;recipient_id:string;amount:number;created_at:string};
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n);
export default function ManagerTeam({profile,onProfile}:WorkspaceViewProps){
 const router=useRouter(); const delegated=!!useSearchParams().get("impersonate"); const [members,setMembers]=useState<Member[]>([]); const [history,setHistory]=useState<Transfer[]>([]);const [balance,setBalance]=useState(0);const [code,setCode]=useState("");const [query,setQuery]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);const [loaded,setLoaded]=useState(false);const [recipient,setRecipient]=useState<Member|null>(null);const [amount,setAmount]=useState("");const request=useRef("");const lock=useRef(false);
 const refresh=useCallback(async()=>{const res=await authFetch("/api/team");const data=await res.json();if(!res.ok)throw Error(data.error||"Could not load team.");setMembers(data.members);setHistory(data.transfers);setBalance(Number(data.balance));setCode(data.code||"");setLoaded(true);return Number(data.balance);},[]);
 useEffect(()=>{if(!delegated)void refresh().catch(e=>setNotice(e.message));},[refresh,delegated]);
 async function open(member:Member){setBusy(true);try{const res=await authFetch("/api/team",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"open",targetId:member.id})});const data=await res.json();if(!res.ok)throw Error(data.error);router.push(`/dashboard?impersonate=${member.id}`);}catch(e){setNotice(e instanceof Error?e.message:"Could not open account.");}finally{setBusy(false);}}
 async function transfer(){if(lock.current||!recipient)return;const cents=Math.round(Number(amount)*100);if(!/^\d+(\.\d{1,2})?$/.test(amount)||cents<=0||cents>Math.floor(balance*100)){setNotice("Enter an amount within your available balance, with up to two decimals.");return;}lock.current=true;setBusy(true);try{const res=await authFetch("/api/team",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"transfer",recipientId:recipient.id,cents,requestId:request.current})});const data=await res.json();if(!res.ok)throw Error(data.error);setRecipient(null);setAmount("");setNotice(`Transferred ${money(cents/100)} to ${recipient.first_name||recipient.email}.`);const latest=await refresh();onProfile({...profile,wallet_balance:latest});}catch(e){setNotice(e instanceof Error?e.message:"Transfer could not be confirmed. Retry this same transfer to check it safely.");}finally{lock.current=false;setBusy(false);}}
 if(delegated)return <Panel><h2>Team administration</h2><p>Exit this account to manage your own team and transfer funds.</p></Panel>;
 return <Panel><div className="v2-panel-head"><div><h2>Manage your team</h2><p>Open assigned accounts, help with daily work, and share your balance.</p></div><button className="v2-btn" onClick={()=>void refresh().catch(e=>setNotice(e.message))}>Refresh</button></div>
 <div className="v2-manager-summary"><div><small>Available to transfer</small><strong>{money(balance)}</strong></div><div><small>Team code</small><strong>{code||"No code assigned"}</strong><span>Teammates join under Workspace & team. Joining grants you access to operate their CRM.</span></div><div><small>Teammates</small><strong>{members.length}</strong></div></div>
 {notice&&<p role="status" className="v2-notice">{notice}</p>}
 <input className="v2-team-search" aria-label="Search teammates" placeholder="Search name or email" value={query} onChange={e=>setQuery(e.target.value)}/>
 <div className="v2-team-list">{members.filter(m=>`${m.first_name} ${m.last_name} ${m.email}`.toLowerCase().includes(query.toLowerCase())).map(m=><div className="v2-team-row" key={m.id}><div><strong>{m.first_name} {m.last_name}</strong><small>{m.email} · {m.paused?"Paused":m.subscription_status}</small></div><strong>{money(Number(m.wallet_balance))}</strong><button className="v2-btn" disabled={busy||m.paused} onClick={()=>void open(m)}>Open account</button><button className="v2-btn primary" disabled={busy||m.paused} onClick={()=>{setRecipient(m);setAmount("");request.current=crypto.randomUUID();setNotice("");}}>Transfer funds</button></div>)}</div>
 {!members.length&&<p>{loaded?"No teammates yet. Share your team code to get started.":"Loading your team…"}</p>}
 <h3 style={{marginTop:24}}>Recent transfers</h3>{!history.length?<p>No transfers yet.</p>:history.map(t=><div className="v2-team-row" key={t.id}><span>{members.find(m=>m.id===t.recipient_id)?.email||"Former teammate"}<small>{new Date(t.created_at).toLocaleString()}</small></span><strong>{money(Number(t.amount))}</strong></div>)}
 {recipient&&<div className="v2-transfer-overlay"><section role="dialog" aria-modal="true" aria-labelledby="transfer-title" className="v2-transfer-dialog"><h2 id="transfer-title">Transfer funds</h2><p>From your wallet to <strong>{recipient.first_name} {recipient.last_name}</strong> ({recipient.email}).</p><p>Available: {money(balance)}. This moves existing account credit and does not charge your card. Transfers cannot be recalled here.</p><label>Amount in dollars<input autoFocus type="text" inputMode="decimal" value={amount} disabled={busy} onChange={e=>{setAmount(e.target.value);request.current=crypto.randomUUID();}} placeholder="25.00"/></label>{notice&&<p role="alert">{notice}</p>}<div><button className="v2-btn" disabled={busy} onClick={()=>setRecipient(null)}>Cancel</button><button className="v2-btn primary" disabled={busy||!amount} onClick={()=>void transfer()}>{busy?"Transferring…":`Confirm transfer${Number(amount)>0?` · ${money(Number(amount))}`:""}`}</button></div></section></div>}
 </Panel>;
}
