"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { MessageSquare, Send, RefreshCw } from "lucide-react";
import { authFetch } from "@/lib/auth-fetch";
type Message={id:string;user_id:string;sender_role:string;message:string;read:boolean;created_at:string};
type Thread={user_id:string;first_name:string;last_name:string;email:string;message:string;created_at:string;unread:number};
export default function SupportChat({admin=false,token,initialUserId=""}:{admin?:boolean;token?:string|null;initialUserId?:string}){
 const [threads,setThreads]=useState<Thread[]>([]);const [selected,setSelected]=useState(initialUserId);const [messages,setMessages]=useState<Message[]>([]);const [draft,setDraft]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [open,setOpen]=useState(!admin||!!initialUserId);const request=useRef("");const sending=useRef(false);const current=useRef(selected);current.current=selected;
 const base=admin?"/api/support?admin=1":"/api/support";
 const call=useCallback((url:string,init?:RequestInit)=>admin?fetch(url,{...init,headers:{...init?.headers,Authorization:`Bearer ${token}`},cache:"no-store"}):authFetch(url,init),[admin,token]);
 const refresh=useCallback(async(signal?:AbortSignal)=>{
  if(admin&&!token)return;
  try{
   if(admin){const r=await call(base,{signal});const d=await r.json();if(!r.ok)throw Error(d.error);setThreads(d.threads);}
   if(!admin||selected){const r=await call(admin?`${base}&userId=${selected}`:base,{signal});const d=await r.json();if(!r.ok)throw Error(d.error);if(current.current===selected)setMessages(d.messages);}
   setError("");setLoading(false);
  }catch(e){if(!signal?.aborted)setError(e instanceof Error?e.message:"Could not refresh chat.");}
 },[admin,token,call,base,selected]);
 useEffect(()=>{const controller=new AbortController();void refresh(controller.signal);const timer=setInterval(()=>{if(document.visibilityState==="visible")void refresh(controller.signal);},10000);return()=>{controller.abort();clearInterval(timer);};},[refresh]);
 async function send(){if(sending.current||!draft.trim()||(admin&&!selected))return;sending.current=true;setBusy(true);const target=selected;request.current||=crypto.randomUUID();try{const r=await call(base,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId:target,message:draft,requestId:request.current})});const d=await r.json();if(!r.ok)throw Error(d.error);setDraft("");request.current="";await refresh();}catch(e){setError(e instanceof Error?e.message:"Message could not be confirmed. Retry safely.");}finally{sending.current=false;setBusy(false);}}
 async function markRead(){if(!messages.length)return;try{const r=await call(base,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId:selected,before:messages[messages.length-1].created_at})});if(!r.ok)throw Error("Could not mark read.");await refresh();}catch(e){setError(e instanceof Error?e.message:"Could not mark read.");}}
 const unread=threads.reduce((sum,t)=>sum+Number(t.unread),0);const active=threads.find(t=>t.user_id===selected);
 const dark=admin;
 return <section id="support-chat" className={`mb-5 overflow-hidden rounded-2xl border ${dark?"border-emerald-400/20 bg-[#0c1820] text-slate-100":"border-slate-200 bg-white text-slate-900"}`} aria-label="Support chat">
 <button onClick={()=>setOpen(!open)} className="flex w-full items-center gap-3 p-4 text-left"><MessageSquare className="h-5 w-5 text-emerald-500"/><span className="flex-1"><strong>{admin?"Customer support inbox":"Chat with Text2Sale support"}</strong><span className={`block text-xs ${dark?"text-slate-300":"text-slate-600"}`}>{admin?"Reply directly to your customers here.":"Send a message to the admin and see replies here."}</span></span>{admin&&<span className="text-sm">{unread} unread</span>}<span>{open?"−":"+"}</span></button>
 {open&&<div className={`border-t ${dark?"border-white/10":"border-slate-200"}`}>
 {error&&<p className={`p-4 text-sm ${dark?"text-amber-200":"text-red-700"}`} role="alert">{error} <button className="underline" onClick={()=>void refresh()}>Retry</button></p>}
 <div className={admin?"grid md:grid-cols-[250px_1fr]":""}>
 {admin&&<div className="max-h-[440px] overflow-y-auto border-r border-slate-500/20 p-2">{!threads.length&&<p className="p-4 text-sm">{loading?"Loading chats…":"No customer chats yet."}</p>}{threads.map(t=><button key={t.user_id} disabled={busy} onClick={()=>{if(draft.trim()&&!window.confirm("Discard this unsent draft and switch conversations?"))return;setSelected(t.user_id);setMessages([]);setDraft("");request.current="";setLoading(true);}} className={`mb-1 w-full rounded-xl p-3 text-left ${selected===t.user_id?"bg-emerald-500/20":"hover:bg-white/5"}`}><strong className="block text-sm">{`${t.first_name||""} ${t.last_name||""}`.trim()||t.email}{Number(t.unread)>0&&<span className="ml-2 text-emerald-300">{t.unread}</span>}</strong><span className="block truncate text-xs text-slate-300">{t.message}</span></button>)}</div>}
 <div className="min-w-0 p-4">{admin&&!selected?<p className="py-12 text-center text-slate-300">Select a customer conversation to reply.</p>:<><div className="mb-3 flex items-center gap-3"><strong className="flex-1 text-sm">{admin?(active?.email||"Customer conversation"):"Your support conversation"}</strong><button className="text-xs underline" onClick={()=>void markRead()}>Mark read</button><button aria-label="Refresh messages" onClick={()=>void refresh()}><RefreshCw className="h-4 w-4"/></button></div>
 <div className="flex max-h-[340px] min-h-[160px] flex-col gap-3 overflow-y-auto" aria-live="polite">{!messages.length&&<p className="py-8 text-center text-sm">{loading?"Loading messages…":"How can we help? Send your first message below."}</p>}{messages.map(m=><article key={m.id} className={`max-w-[90%] rounded-xl p-3 ${m.sender_role===(admin?"admin":"user")?"self-end bg-emerald-600 text-white":dark?"self-start bg-slate-800 text-slate-100":"self-start bg-slate-100 text-slate-900"}`}><small className="font-semibold">{m.sender_role==="admin"?"Text2Sale support":"Customer"}</small><p className="whitespace-pre-wrap break-words text-sm">{m.message}</p><time className="mt-2 block text-[10px] opacity-80">{new Date(m.created_at).toLocaleString()}</time></article>)}</div>
 <form onSubmit={e=>{e.preventDefault();void send();}} className="mt-4"><label className="mb-2 block text-xs" htmlFor={admin?"admin-reply":"support-message"}>{admin?"Reply to this customer":"Message support"}</label><textarea id={admin?"admin-reply":"support-message"} value={draft} disabled={busy} maxLength={4000} onChange={e=>{setDraft(e.target.value);request.current="";}} rows={3} className={`w-full rounded-xl border p-3 text-sm ${dark?"border-slate-600 bg-slate-900 text-white":"border-slate-300 bg-white text-slate-900"}`} placeholder="Type your message…"/><div className="mt-2 flex items-center justify-between"><small>{draft.length}/4,000 · Latest 100 messages</small><button disabled={busy||!draft.trim()} type="submit" className="flex items-center gap-2 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50"><Send className="h-4 w-4"/>{busy?"Sending…":"Send message"}</button></div></form></>}</div></div></div>}
 </section>;
}
